//
// Created by JiangGuoqing on 2018/10/15.
//

#ifndef DG_ERROR_H_
#define DG_ERROR_H_

typedef enum {
    DG_OK = 0,

    DG_ON_GOING = 1,

    DG_ERR_NOT_EXIST = 2,
    DG_ERR_ALREADY_EXIST = 3,
    DG_ERR_NOT_SUPPORTED = 4,
    DG_ERR_NOT_ALLOWED = 5,
    DG_ERR_OVERFLOW = 6,
    DG_ERR_SERVICE_NOT_AVAILABLE = 7,
    DG_ERR_ASYNC_NOT_SUPPORTED = 8,
    DG_ERR_OP_REJECT_INPUT = 9,
    DG_ERR_OP_CREATE_FAIL = 10,
    DG_ERR_UNKNOWN_URL = 11,
    DG_ERR_MEMORY_SHORTAGE = 12,
    DG_ERR_REACH_END = 13,
    DG_ERR_INFERENCE_REQ_FAIL = 14,
    DG_ERR_SEND_MSG = 15,
    DG_ERR_GRAPH_NOT_EXIST = 16,
    DG_ERR_GRAPH_USED_BEFORE_CREATION = 17,
    DG_ERR_UNKNOWN_GRAPH_TYPE = 18,
    DG_ERR_GRAPH_OPEN_FAIL = 19,
    DG_ERR_STREAM_NOT_EXIST = 20,
    DG_ERR_PLATFORM_NOT_EXIST = 21,
    DG_ERR_IMAGE_LOAD_FAIL = 22,
    DG_ERR_SINGLE_INSTANCE_ONLY = 23,
    DG_ERR_SINGLE_INSTANCE_NOT_EXIST = 24,
    DG_ERR_PB_DECODE_FAIL = 25,
    DG_ERR_PB_ENCODE_FAIL = 26,
    DG_ERR_INVALID_PARAM = 27,
    DG_ERR_INVALID_ADDRESS = 28,
    DG_ERR_INVALID_IMAGE = 29,
    DG_ERR_INVALID_MEMORY = 30,
    DG_ERR_HW_FAILURE = 31,
    DG_ERR_SAFENET_CODE_ERR = 32,
    DG_ERR_OP_CREATE_INCORRECT = 33,
    DG_ERR_INIT_FAIL = 34,
    DG_ERR_DEINIT_FAIL = 35,
    DG_ERR_ENGINE_CREATE_FAIL = 36,
    DG_ERR_BORDER_FACE = 37,
    DG_ERR_ABORTED = 38,
    DG_ERR_OPEN_FILE_FAIL = 39,
    DG_ERR_VENC_FAIL = 40,
    DG_ERR_CANCELLED = 41,
    DG_ERR_STREAM_FAILURE = 42,
    DG_ERR_FULL = 43,
    DG_ERR_VDEC_FAIL = 44,
    DG_ERR_REMOVE_FILE_FAIL = 45,
    DG_ERR_MKDIR_FAIL = 46,
    DG_ERR_DECODE_FAIL = 47,
    DG_ERR_TIME_OUT = 48,
    DG_ERR_MALI_ERR = 49,
    DG_ERR_IMAGE_EXCEEDS_CAPABILITY = 50,
    DG_ERR_FSE_DECRYPT_FEATURE_FAIL = 51,
    DG_ERR_EXCEED_AUTHO_LIMIT = 52
} DgError;
#endif //DG_ERROR_H_
